### ISSUE TITLE
Use `argparse` for parsing command-line args

### ISSUE THREAD

**Issue by aaaaalbert** [TheTesla/cryptdomainmgr#1]
The cleanup/prepare/rollover/update scripts currently use the `sys` module to access `argv` and parse command-line arguments ([see here for example](https://github.com/TheTesla/cryptdomainmgr/blob/afcaf5053dee2348f9b6ab23ce1b48ae00aeb25b/cleanup.py#L14-L20)).

Instead of manual `argv` treatment, I suggest using `argparse` which is cleaner and has other benficial side-effects (like providing super-simple self-documentation for commands).

**Comment by TheTesla** [comment]
Is done now. Call:
python -m cryptdomainmgr -h
for more information.

**Comment by aaaaalbert** [comment]
Cool!

(For reference, 113e00f76980c3f7952cef65e8cc9ad06aad2149 adds `argparse` to `cryptdomainmgr.py` which is called `__main__.py` since c4ce2e5fb240d474ceefc814e6779fbd8623cb4c).
